name: Build LaTeX

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Check out code
      uses: actions/checkout@v4

    - name: Build LaTeX
      uses: xu-cheng/texlive-action/full@v1
      with:
        run: make

    - name: Upload PDF artifact
      uses: actions/upload-artifact@v3
      with:
        name: master
        path: master.pdf
